services:
  - type: web
    name: school-manager
    env: dotnet
    buildCommand: dotnet publish -c Release
    startCommand: dotnet SchoolManager.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=dpg-d0nqgl7diees73cvjfjg-a.oregon-postgres.render.com;Port=5432;Database=schoolmanager_1226a_hf8s;Username=schoolmanager_1226ab;Password=iupnt5ySTMLaGkb6I7j8xWtIHDdfs9ym;SSL Mode=Require;Trust Server Certificate=true;"

databases:
  - name: school-manager-db
    databaseName: schoolmanager_1226a_hf8s
    user: schoolmanager_1226ab
    plan: free